import {
  Target,
  Gear,
  Sparkle,
  MagnifyingGlass,
  PencilSimple,
  Palette,
  Package,
  Lightning,
  TreeStructure,
  PenNib,
  Strategy,
  Users,
  ChatsCircle,
  MapTrifold,
  Path,
  Layout,
  Stack,
  Cube,
  Eye,
  Ruler,
  Browsers,
  DeviceMobile,
  CursorClick,
  ArrowsOutCardinal,
  Heart,
  ArrowClockwise,
  ShieldCheck,
  Warning,
  ListChecks,
  Clock,
  FigmaLogo,
  Brain,
  Compass,
  Books,
  Quotes,
  PuzzlePiece,
  GridFour,
  Stamp,
  Export,
  Devices,
  HandPointing,
  TestTube,
  NotePencil,
  Question,
  Check,
  ArrowRight,
  ArrowsLeftRight,
  Graph,
  Lightbulb,
  FlowArrow,
  Article,
  SlidersHorizontal,
} from "@phosphor-icons/react";

export const ICONS = {
  useful: Target,
  usable: Gear,
  desirable: Sparkle,
  research: MagnifyingGlass,
  design: PencilSimple,
  ui: Palette,
  product: Package,
  interaction: Lightning,
  ia: TreeStructure,
  writer: NotePencil,
  strategy: Strategy,
  architect: TreeStructure,
  users: Users,
  interview: ChatsCircle,
  journey: MapTrifold,
  scenario: FlowArrow,
  ideation: Lightbulb,
  jtbd: Target,
  empathy: Heart,
  ai: Brain,
  perplexity: Compass,
  synthesis: Graph,
  figma: FigmaLogo,
  vector: PenNib,
  layout: Layout,
  autolayout: SlidersHorizontal,
  system: Stack,
  variables: GridFour,
  boolean: PuzzlePiece,
  components: Cube,
  prototype: CursorClick,
  paper: Article,
  micro: Lightning,
  states: Stack,
  test: TestTube,
  multidevice: Devices,
  touch: HandPointing,
  principles: Ruler,
  visibility: Eye,
  atomic: GridFour,
  component: Cube,
  handoff: Export,
  devmode: Browsers,
  portfolio: Books,
  capstone: Stamp,
  check: Check,
  arrow: ArrowRight,
  swap: ArrowsLeftRight,
  clock: Clock,
  question: Question,
  quote: Quotes,
  list: ListChecks,
  warn: Warning,
  loop: ArrowClockwise,
  shield: ShieldCheck,
  ruler: Ruler,
  mobile: DeviceMobile,
  path: Path,
  devices: Devices,
  browsers: Browsers,
  arrows: ArrowsOutCardinal,
} as const;

export type IconKey = keyof typeof ICONS;
