/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        nv: "#0D1B2E",
        nm: "#1A2F4A",
        ns: "#0B1520",
        go: "#B8953F",
        gl: "#D4A84A",
        gx: "#ECC05A",
        cr: "#FDFAF5",
        wh: "#FFFFFF",
        t1: "#0D1B2E",
        t2: "#334155",
        t3: "#64748B",
      },
      fontFamily: {
        display: ['"Geist Variable"', "Inter", "system-ui", "sans-serif"],
        body: ["Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        chrome: ["18px", { lineHeight: "1.2", letterSpacing: "0.045em" }],
        eyebrow: ["20px", { lineHeight: "1.2", letterSpacing: "0.13em" }],
        small: ["21px", { lineHeight: "1.5" }],
        body: ["26px", { lineHeight: "1.55" }],
        cardbody: ["22px", { lineHeight: "1.5" }],
        cardtitle: ["26px", { lineHeight: "1.15" }],
        lead: ["30px", { lineHeight: "1.5" }],
        h2: ["44px", { lineHeight: "1.08", letterSpacing: "-0.3px" }],
        h1: ["64px", { lineHeight: "1.0", letterSpacing: "-0.6px" }],
        stmt: ["76px", { lineHeight: "1.07", letterSpacing: "-0.8px" }],
        cover: ["100px", { lineHeight: "0.93", letterSpacing: "-2px" }],
        divider: ["88px", { lineHeight: "0.97", letterSpacing: "-1.5px" }],
      },
      spacing: {
        s1: "8px",
        s2: "16px",
        s3: "24px",
        s4: "28px",
        s5: "32px",
        s6: "36px",
        s7: "48px",
        s8: "56px",
        s9: "64px",
        s10: "72px",
        s11: "96px",
      },
      borderRadius: { card: "18px", chip: "12px", pill: "999px" },
      boxShadow: {
        card: "0 2px 14px rgba(0,0,0,0.055)",
        cardlg: "0 4px 24px rgba(0,0,0,0.10)",
      },
      maxWidth: { stage: "1920px" },
    },
  },
  plugins: [],
};
